language: ruby
cache: bundler
rvm:
- 2.4
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
  - gh-pages
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
before_deploy:
- git config --local user.name "YOUR GIT USER NAME"
- git config --local user.email "YOUR GIT USER EMAIL"
- echo -e "\n\n\nbefore_deploy\n\n\n"
- echo echoing the site directory
- ls /home/travis/build/ccram-website/ccram-website.github.io/_site/
  
deploy:
  provider: script
  file_glob: true
  file: /home/travis/build/ccram-website/ccram-website.github.io/_site/**/*
  skip_cleanup: true
  script: echo -e "\n\n\ndeploy\n\n\n"
  on:
    repo: ccram-website/ccram-website.github.io
    branch: master
