language: ruby
cache: bundler
rvm:
- 2.3.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
  - gh-pages
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
before_deploy:
- git config --local user.name "YOUR GIT USER NAME"
- git config --local user.email "YOUR GIT USER EMAIL"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: S+7ZhTMpDW5zWScurBNdtxYvg4z5fM45zuKPGS3YXI97rhKYOkoj/Q1tWthAtCX7MGEe0TDn7ZdXlgIOTREXMYX6l7rn97VmUVcg/cvu7w6n+RsUCAdvWOxcwtdiLpaYCdleUDZ28yHIIVQ8AQ5UX5HiZZzx5MRGtQ2EaRxg1hqifc6YmC/fgi8mom0RLWAV7QlW7uYMQcLG3NjZbGUR+QuL2yk0FT7FAiqX0X9CjD1CraWPZWyXcDWgLMuqYjSkgHmsPHGoPBprwNFaJw79WsM1prHc9v+tZLQNRgxuoiwBpo5ZnlacbIcJruINioS101/DplGNfoW4M3pwqDYiook8IedUA+tyqwMG2ffwL2V6vh5zm/mcTXq4IDu5Y4rlY2TcoNDU72njyg4FQJs6tkjBy7xlEJit308q0VIYc14qhZYb/J4JUMRcxOWgD059SKTRjyLr6QZdpXWHFhKV8h9rgo6lP3Y+rrYShvGI48m/qA+WgjepsqvxDDDkRLLWeWS87Q08DppJjCAZjo3utKiyRA8VmtQMjzWs5bwifV5Ao745jd9Qit8uaV+IvG4S37xdBE5wak/gHdhgFKMyZQhxB07xAgC7pjpiqiHu6A6xMjHkLufBSZc39+PksgBL8c8EpqX72qOpYd1fohPdB3wUtnJeS6XO5FijS+iSOKU=
  file: index.html
  on:
    repo: ccram-website/ccram-website.github.io
