#!/usr/bin/env bash
set -e # halt script on error

echo -e "\n\n\nscript/cibuild\n\n\n"
echo $(pwd)
bundle install
bundle exec jekyll build
echo $(pwd)
cd /home/travis/build/ccram-website/ccram-website.github.io/
zip -r _site.zip _site
ls
